### ISSUE TITLE
Theorem 11: Bernstein 不等式 最后部分，我反复代入算不出来结果？

### ISSUE THREAD

**Issue by BinFuPKU** [datawhalechina/key-book#13]
<img width="750" alt="截屏2021-10-08 下午6 06 16" src="https://user-images.githubusercontent.com/29002864/136538371-f4584931-44e3-48d6-8248-fbb39a08d07d.png">
<img width="439" alt="截屏2021-10-08 下午6 07 16" src="https://user-images.githubusercontent.com/29002864/136538433-b62a4c76-2f25-4bb2-bd5b-fc54159dd824.png">
你们代入看看，能不能得到证明的结果，我这边试了几次，得不到证明结果。

**Comment by leafy-lee** [comment]
已修正
