### ISSUE TITLE
PDF release is empty

### ISSUE THREAD

**Issue by Allencheng97** [datawhalechina/key-book#52]
Hi authors,
 
  Thank you very much for your great work! I am wondering where i could download the latest version pdf. I tried to open the webpage in the readme https://github.com/datawhalechina/key-book/releases  but the release is empty now.

Thank you for your time and i am looking forward to hearing from you soon.

Best

**Comment by zhimin-z** [comment]
> Hi authors,
> 
> Thank you very much for your great work! I am wondering where i could download the latest version pdf. I tried to open the webpage in the readme https://github.com/datawhalechina/key-book/releases but the release is empty now.
> 
> Thank you for your time and i am looking forward to hearing from you soon.
> 
> Best

Thanks for your interest along with inquiry, we have fixe this issue already recently. Now you can find the PDF, HTML, and MD version of the releases in the aforementioned ULR.
